# Generated by Django 5.2.7 on 2026-09-29 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('alternate_contact_name', models.CharField(max_length=160)),
                ('age', models.PositiveSmallIntegerField()),
                ('birth_date', models.DateField()),
                ('personal_phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+52\\d{10}$', 'El teléfono debe almacenarse como +52 seguido de 10 dígitos.')])),
                ('street', models.CharField(max_length=160)),
                ('neighborhood', models.CharField(max_length=120)),
                ('municipality', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'El código postal debe tener 5 dígitos.')])),
                ('personal_email', models.EmailField(max_length=254)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.FileField(upload_to='clients/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name', 'id'],
            },
        ),
    ]
